
user-agent: HvyD
owner: HvyD
repo: UpTime_monitor

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Add your sites here
sites:
  - name: Scott W. Davis Portfolio Site
    url: https://www.scottwdavis.tech
  - name: MonkeyMommaCreations Blog and Store Site
    url: https://www.monkeymommacreations.com

status-website:
  baseUrl: https://hvyd.github.io/UpTime_monitor/
  name: Status Site
