# Change these first
owner: HvyD # Your GitHub username
repo: UpTime_monitor # Your GitHub repository name

# Add your sites here
sites:
  - name: HvyD
    url: http://www.hvyd.us
    
  - name: monkeyMommaCreations
    url: https://www.monkeymommacreations.com

status-website:
  baseUrl: https://HvyD.github.io/repo/UpTime_monitor # where "repo" is your repository name
  name: Status Site
