# Change these first
owner: HvyD # Your GitHub username
repo: UpTime_monitor # Your GitHub repository name

# Add your sites here
sites:
  - name: HvyD
    url: http://www.hvyd.us
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: monkeyMommaCreations
    url: https://www.monkeymommacreations.com
    expectedStatusCodes:
      - 200
      - 201
      - 404
